- aten/src/ATen/native/mps/operations/RangeFactories.mm
The comparison earlier was being made between the start and end constant double values, which were not a part of the graph; we needed to compare start and end tensors
> Fix linspace conditional clamp

- aten/src/ATen/native/mps/operations/Copy.mm
- test/test_mps.py
> Fix view copies for cpu->mps case; add testcase

- aten/src/ATen/native/mps/OperationUtils.mm
Add tensor dtype in key generation
> Add tensor dtype in key generation

- aten/src/ATen/native/mps/OperationUtils.h
- aten/src/ATen/native/mps/OperationUtils.mm
- aten/src/ATen/native/mps/operations/BinaryOps.mm
- aten/src/ATen/native/mps/operations/UnaryOps.mm
- test/test_mps.py
> Cast BinaryOps tensors to proper types (#78879)

- aten/src/ATen/native/mps/operations/Distributions.mm
- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
This is needed for multinomial without replacement
> Add exponential distribution

- aten/src/ATen/native/mps/operations/Normalization.mm
- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
Will let us run hf_Bert
Not tested for ChannelsLast input
> Layernorm backward

- aten/src/ATen/native/mps/operations/Shape.mm
- test/test_mps.py
> TopK raise an error if K>16

- aten/src/ATen/native/mps/operations/Linear.mm
- test/test_mps.py
Fixes https://github.com/pytorch/pytorch/issues/79784
Branch name is wrong, because I thought the issue is in MSE
> Fix handling of 1D tensors in linear backward

- aten/src/ATen/mps/MPSAllocator.mm
- aten/src/ATen/native/mps/operations/Copy.mm
- aten/src/ATen/native/mps/operations/View.mm
This should improve the performance
> Don't wait when copying from MPS to MPS tensors

- aten/src/ATen/native/mps/operations/Shape.mm
- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
New op.
Added the op, test case & native_functions.yaml changes.
> Added op upsample_nearest1d

- test/test_mps.py
Add testcase from https://github.com/pytorch/pytorch/issues/80856 in test_mps.py
> Add testcase for issue 80856

- aten/src/ATen/native/mps/OperationUtils.mm
Fix truncation of MPSShape from int64_t to int32_t
> Fix truncation of MPSShape from int64_t to int32_t

- aten/src/ATen/native/mps/operations/LinearAlgebra.mm
Fixes https://github.com/pytorch/pytorch/issues/80288
> Handle 1D bias for addmm

- aten/src/ATen/mps/MPSDevice.mm
> Fix the compile failure.

- aten/src/ATen/native/mps/operations/Repeat.mm
- test/test_mps.py
Handle the case where array of repeat dimensions is empty
> Repeat crash fix

- aten/src/ATen/native/mps/operations/LossOps.mm
- test/test_mps.py
Fix testConsistency issue (smooth l1 was failing for float16 input)
> Smooth l1 type fix

- aten/src/ATen/mps/MPSStream.h
- aten/src/ATen/mps/MPSStream.mm
- aten/src/ATen/native/mps/OperationUtils.h
- aten/src/ATen/native/mps/operations/BinaryOps.mm
- aten/src/ATen/native/mps/operations/ConstantOps.mm
Fix minor bug in add_sub_template() with value=0.0
Change default value of use_scalar_value to false in getTensorsStringKey()
> Use fillBuffer() for zero_mps()

- aten/src/ATen/mps/IndexKernels.h
- aten/src/ATen/native/mps/OperationUtils.h
- aten/src/ATen/native/mps/OperationUtils.mm
- aten/src/ATen/native/mps/operations/Indexing.mm
- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
Fixes https://github.com/pytorch/pytorch/issues/77764#issuecomment-1145905264, https://github.com/pytorch/pytorch/issues/77764#issuecomment-1172127562, https://github.com/pytorch/pytorch/issues/77764#issuecomment-1143166880, https://github.com/pytorch/pytorch/issues/77764#issuecomment-1140196361 (from page https://github.com/pytorch/pytorch/issues/77764)
> Add support for aten::index_put_impl

- aten/src/ATen/mps/MPSStream.mm
- aten/src/ATen/native/mps/operations/View.mm
> Change commitAndWait to Commit in View Ops

- aten/src/ATen/native/mps/operations/Linear.mm
- aten/src/ATen/native/mps/operations/LinearAlgebra.mm
> Handle int inputs of matmul ops

- aten/src/ATen/native/mps/operations/Shape.mm
- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
This should improve the performance in several benchmarks
> Add MPS implementation for constant_pad_nd()

- aten/src/ATen/native/mps/operations/LinearAlgebra.mm
Fix empty input and unnecessary transposing in matmul
> Matmul crash errors

- aten/src/ATen/native/mps/operations/Convolution.mm
- test/test_mps.py
Fixes https://github.com/pytorch/pytorch/issues/81557
Fixes NCHW -> NHWC layout conversion for Conv 1D.
> Add support for conv1d channels last memory format

- aten/src/ATen/native/mps/operations/Convolution.mm
- test/test_mps.py
Fixes https://github.com/pytorch/pytorch/issues/81557
> Initialize IntArrayRef correctly on release builds

- aten/src/ATen/mps/IndexKernels.h
- aten/src/ATen/mps/MPSDevice.mm
- aten/src/ATen/native/mps/OperationUtils.h
- aten/src/ATen/native/mps/OperationUtils.mm
- aten/src/ATen/native/mps/operations/Indexing.h
- aten/src/ATen/native/mps/operations/Indexing.mm
- test/test_mps.py
- Move the index offset calculation on GPU
- Reduce the time to run test_mps.py from ~20s to ~5s
> Move the index offset calculation on GPU

- aten/src/ATen/mps/MPSDevice.mm
- aten/src/ATen/native/mps/OperationUtils.h
- aten/src/ATen/native/mps/OperationUtils.mm
- aten/src/ATen/native/mps/operations/Indexing.mm
> Address remaining PR comments

- aten/src/ATen/native/mps/OperationUtils.h
- aten/src/ATen/native/mps/OperationUtils.mm
- aten/src/ATen/native/mps/operations/Indexing.mm
> Fix the index_select for non FP32 types.

- aten/src/ATen/native/mps/operations/ReduceOps.mm
Edge case where input tensor is 0 dimensional
> Handle reduction of scalars

- aten/src/ATen/mps/MPSAllocator.h
- aten/src/ATen/mps/MPSAllocator.mm
- aten/src/ATen/mps/MPSDevice.mm
- aten/src/ATen/mps/MPSStream.h
- aten/src/ATen/mps/MPSStream.mm
- aten/src/ATen/native/mps/OperationUtils.h
- aten/src/ATen/native/mps/OperationUtils.mm
- aten/src/ATen/native/mps/operations/BinaryOps.mm
- aten/src/ATen/native/mps/operations/Indexing.mm
- aten/src/ATen/native/mps/operations/PointwiseOps.mm
- aten/src/ATen/native/mps/operations/RangeFactories.mm
- aten/src/ATen/native/mps/operations/View.mm
- Add buffer usage and debug verbosity flags to MPSAllocator (and clean up)
> Use specialized memory pool to import scalar values to Metal buffers

- aten/src/ATen/native/mps/operations/BinaryOps.mm
- test/test_mps.py
So that integer division can have correct rounding
> Handle casting for div operation

- aten/src/ATen/native/mps/operations/TensorCompare.mm
- test/test_mps.py
Fix test consistency issue for clamp ops - now gives correct result
> Clamp op - fix shape issues

- aten/src/ATen/native/mps/operations/Linear.mm
- test/test_mps.py
> Linear with 1d weights

- aten/src/ATen/native/mps/operations/ScatterGather.mm
- test/test_mps.py
Issue noticed in test consistency - "Indexing dim 0 is out of bounds of tensor"
> Handle scalar input for scatter and gather

- aten/src/ATen/native/mps/operations/Normalization.mm
- test/test_mps.py
Issue observed in TestConsistency
> Handle empty input in layer norm

- aten/src/ATen/native/mps/operations/Pad.mm
- test/test_mps.py
> Fix the dimension of padding to match the input's dimension

- aten/src/ATen/core/PhiloxRNGEngine.h
- aten/src/ATen/native/mps/operations/Pad.mm
- test/test_mps.py
Also fixed some lint issues and removed an unused variable.
Fixes #84535
> Fix the error with constant_pad_nd for 4D+ padding

- aten/src/ATen/native/mps/operations/Copy.mm
- test/test_mps.py
Fixes https://github.com/pytorch/pytorch/issues/83995 and https://github.com/pytorch/pytorch/issues/84489
> Fix slice from view tensors

- aten/src/ATen/native/mps/operations/Blas.mm
- test/test_mps.py
Fixes dot output for int16 and uint8 inputs
> Cast dot inputs to int32 when needed

- aten/src/ATen/native/mps/operations/View.mm
Improves the torch.rand() performance mentioned in #77799
> Replace the explicit commit in View ops with adaptive commit

- aten/src/ATen/native/mps/OperationUtils.mm
> [MPS] Don't reset the Graph options and leave it to default

- aten/src/ATen/native/mps/operations/ReduceOps.mm
- aten/src/ATen/native/mps/operations/SummaryOps.mm
- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
Add support for bincount on MPS
> Add bincount support for mps

- aten/src/ATen/native/mps/operations/ReduceOps.mm
- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
Register norm_dtype_out for mps
> Register norm_dtype_out for mps

- aten/src/ATen/native/mps/operations/Linear.mm
- Also Clean up redundant headers and namespaces from Linear.mm 
This should improve the Bert sample in #77799 by ~3x
> Improve the performance of torch.linear()

- aten/src/ATen/native/mps/operations/BinaryOps.mm
- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
This should fix the error with hf_BigBird
> Add floor_divide() op and its test case

- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
Move some working ops from block list to allow list
> Unregister put() for MPS backend

- test/test_nn.py
> Fix the skipIfMps include in header.

- aten/src/ATen/native/mps/operations/Convolution.mm
The bug was mentioned in :
https://github.com/pytorch/pytorch/issues/77764#issuecomment-1312241902
> Fix the Channels last bug with GradientWithInput.

- aten/src/ATen/native/mps/operations/ScatterGather.mm
- test/test_mps.py
Also fix float16 for scatter_add()
> Fix cast issue in scatter() with uint8 type 

- aten/src/ATen/native/mps/operations/Pad.mm
- test/test_mps.py
Also fix the assert with bool type in constant padding
> Fix GPU timeout caused by negative padding in backward pass

- aten/src/ATen/native/mps/operations/TensorCompare.mm
- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
Added a test case, and also enabled it in TestConsistency
> Implement nan_to_num() for MPS backend

- aten/src/ATen/native/mps/OperationUtils.h
- aten/src/ATen/native/mps/OperationUtils.mm
- aten/src/ATen/native/mps/operations/Pooling.mm
- test/test_mps.py
- Workaround for MaxPool when ceilMode=true
- Workaround for ChannelsLast memory format
- Workaround for divisor_override in AvgPool ops
- Enabled count_include_pad parameter for AvgPool
- Refactoring and clean up of duplicate code
> Fix correctness issues with Pooling ops

- aten/src/ATen/native/mps/operations/Pad.mm
- test/test_mps.py
- Workaround for the bool type bug in padding (needed for both Monterey and Ventura)
> Workaround for the right padding bug in Monterey

- aten/src/ATen/native/mps/operations/Inverse.mm
Same as https://github.com/pytorch/pytorch/pull/90428
> Inverse op fallback (op/inverse)

- aten/src/ATen/native/mps/operations/Pooling.mm
- test/test_mps.py
Also skip the test on TestConsistency when such errors are generated
> Display error for int64 pooling inputs on Monterey

- aten/src/ATen/native/mps/operations/ReduceOps.mm
- test/test_mps.py
Also move some expected int64 errors from block list to allow list
> Replace assert() with torch_check() in reduce ops

- aten/src/ATen/native/mps/OperationUtils.h
- aten/src/ATen/native/mps/OperationUtils.mm
- aten/src/ATen/native/mps/operations/BinaryOps.mm
- test/test_mps.py
Also fix the signed vs. unsigned cast issue for Monterey.
> Fix uint8 issues in BinaryOps for Monterey

- aten/src/ATen/native/mps/operations/UnaryOps.mm
- test/test_mps.py
> Make intermediate type for cumsum ScalarType::Int

- aten/src/ATen/mps/MPSAllocator.h
- aten/src/ATen/mps/MPSAllocator.mm
- aten/src/ATen/mps/MPSAllocatorInterface.h
- aten/src/ATen/mps/MPSDevice.mm
- aten/src/ATen/mps/MPSStream.mm
- aten/src/ATen/native/mps/OperationUtils.mm
- aten/src/ATen/native/mps/operations/Unique.mm
- aten/src/ATen/native/mps/operations/View.mm
This is a prerequisite for the Memory Stats and Memory Leak Detection features
> Add MPSAllocatorInterface to access methods of MPSAllocator

- aten/src/ATen/native/mps/operations/BinaryOps.mm
- aten/src/ATen/native/mps/operations/View.mm
- test/test_mps.py
Fixes slices followed by reshapes
> Fix slice followed by reshape

- aten/src/ATen/native/mps/operations/Indexing.mm
- test/test_mps.py
- changing alphaTensor type into using self.scalar_type()
- remove index_add from blocklist
- block bool,int16,int64,float16,uint8 as scatterWithDataTensor giving wrong results
> Fix index_add type issue

- aten/src/ATen/native/mps/operations/Convolution.mm
> Block conv_transpose3d

- aten/src/ATen/native/mps/operations/ReduceOps.mm
> [MPS] Casting int64 to int32 for reduction ops.

- aten/src/ATen/native/mps/operations/Activation.mm
- test/test_mps.py
- fix gelu_backward_out_mps key
- uniform format
- add caculation for tanh approximate backward pass
- unblock grad test from blocklist
> Fix gelu backward

- test/test_mps.py
Cumulative_trapezoid is passing in test_mps, can be removed from blocklist
> Remove cumulative_trapezoid from blocklist

- aten/src/ATen/native/mps/operations/Convolution.mm
This helps with performance in MobileNet, NasNet etc.
> [MPS] Map Conv to Depthwise when input_channels==same as num_groups.

- aten/src/ATen/native/mps/operations/Shape.mm
- test/test_mps.py
mps cat out tensor is always contiguous.
> disable cat pre&post transpose

- aten/src/ATen/native/mps/operations/LinearAlgebra.mm
- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
- addr_out_mps to perform res = beta*input + alpha*(vec1Xvec2)
- move addr f16 to low precision list
- move addr none float to unsupported list
- add test_addr tests
> Native implementation for addr

- aten/src/ATen/native/mps/operations/ConstantOps.mm
- test/test_mps.py
- The self was not contiguous and inline filling produced wrong results
- Added a test case for the issue
Fixes #94190
> Fix correctness issue with fill_scalar_mps()

- aten/src/ATen/mps/MPSDevice.mm
- aten/src/ATen/native/mps/operations/Inverse.mm
- aten/src/ATen/native/mps/operations/ReduceOps.mm
- test/test_mps.py
Fixes empty placeholder error in inverse op. Change to any op should also resolve previously seen segfaults
> Added zero check to inverse & fix for any op to avoid segfault issue

- Makefile
- aten/src/ATen/native/mps/operations/ReduceOps.mm
- aten/src/ATen/native/mps/operations/Shape.mm
- test/test_mps.py
> [MPS] Add support for TopK k>16

- aten/src/ATen/native/mps/operations/Activation.mm
Fixes test_modules.py tests:
- test_memory_format_nn_Hardswish_mps_float32
- test_non_contiguous_tensors_nn_Hardswish_mps_float32
- test_memory_format_nn_ReLU_mps_float32
> Fix test modules memory format issues for ReLU and Hardswish

- .github/workflows/_mac-test-mps.yml
- .github/workflows/lint.yml
- test/test_modules.py
* Enable test modules on MPS and CI runners
> [cherry-pick] Enable test modules on MPS and CI runners (#305)

- aten/src/ATen/native/mps/operations/RnnOps.mm
- test/test_mps.py
Change takes into account the changed shape of the input params TensorList depending on the bias flag.
> Fixes crash when lstm op called with has_biases set to false

- aten/src/ATen/native/mps/operations/Activation.mm
Fixes a bug where the inputTensor in line 1285 could go null and cause a crash:
`MPSGraphTensor* predicateTensor = [mpsGraph greaterThanWithPrimaryTensor:inputTensor`
> Fix the crash in elu_backward()

- aten/src/ATen/native/mps/operations/Indexing.mm
- test/test_mps.py
- casting the input tensor to float32 and cast back the output tensor
- unblock the test
> Fix nn.functional.embedding grad

- aten/src/ATen/native/mps/operations/Activation.mm
- test/test_mps.py
Allocate the correct shape for the weights gradient
> Fix prelu backward pass

- aten/src/ATen/native/mps/operations/UpSample.mm
- test/test_mps.py
Fixes https://github.com/huggingface/diffusers/issues/941
**Before**:
**After**:
> Fix upsample for NHWC output

- aten/src/ATen/native/mps/operations/Indexing.mm
https://github.com/pytorch/pytorch/actions/runs/4189302281/jobs/7261452227
> [DOWNSTREAM] Fix build failure on CI runners

- aten/src/ATen/native/mps/operations/ReduceOps.mm
- test/test_mps.py
- give warnings of converting int64 for reduction ops
- use cast tensor for reduction sum on trace
- unblock trace from running
> Fix trace op

- test/test_mps.py
- move nn.functional.feature_alpha_dropoutwith_train, normalnumber_mean, new_empty_strided to expected failures
> Update random result list

- aten/src/ATen/native/mps/operations/Convolution.mm
Removes wrong conditions from Convolution transpose code
> Convolution cleanup

- aten/src/ATen/mps/MPSFallback.mm
- aten/src/ATen/native/mps/operations/Convolution.mm
> [MPS] Adding the checks for Convolution and removing FFT from fallback

- .github/actionlint.yaml
- .github/requirements-gha-cache.txt
- .github/workflows/_mac-test-mps.yml
- .github/workflows/lint.yml
- .github/workflows/mac-mps.yml
- test/test_mps.py
- test/test_mps_utils.py
Enable 13.3 in CI
Build wheels for 3.8 and 3.9
> Enable 13.3 in CI

- aten/src/ATen/native/mps/operations/BinaryOps.mm
- aten/src/ATen/native/mps/operations/UnaryOps.mm
- test/test_mps.py
- throw an error for trunc div float16
> Block trunc divide for float16

- aten/src/ATen/native/mps/operations/View.mm
- test/test_mps.py
Fixes https://github.com/pytorch/pytorch/issues/95482
> Fix views with 3 or more sliced dimensions

- test/test_mps.py
- tools/autograd/derivatives.yaml
> Add parentheses to atanh grad to ensure correct output

- .github/pytorch-probot.yml
- .github/scripts/run_torchbench.py
- .github/workflows/run_torchbench.yml
> Run torchbench on CI

- aten/src/ATen/mps/MPSStream.h
- aten/src/ATen/mps/MPSStream.mm
- aten/src/ATen/native/mps/OperationUtils.h
- aten/src/ATen/native/mps/OperationUtils.mm
- aten/src/ATen/native/mps/operations/BinaryOps.mm
- aten/src/ATen/native/mps/operations/ReduceOps.mm
- aten/src/ATen/native/mps/operations/UnaryOps.mm
> Cache the MPSGraphExecutable in MPSCachedGraph for reusing

- aten/src/ATen/native/mps/operations/Pad.mm
- test/test_mps.py
- Only ReflectPad needs the torch checks and not ReplicatePad
> Fix the failure with ReplicatePad3D

- aten/src/ATen/mps/MPSFallback.mm
- aten/src/ATen/native/mps/operations/ReduceOps.mm
- aten/src/ATen/native/native_functions.yaml
- test/test_mps.py
Summary of changes:
- Add support for linalg.vector_norm
- Fix zero norm, correct formula is: `sum(x != 0)`
- Add additional tests in test_mps
> Add support for linalg.vector_norm

- aten/src/ATen/native/mps/operations/BinaryOps.mm
> Reuse existing buffer for inplace operations (for offset 0)

- aten/src/ATen/mps/MPSFallback.mm
- torch/backends/mps/__init__.py
> [MPS] Register im2col and col2im through decompositions.

- aten/src/ATen/mps/MPSStream.h
- aten/src/ATen/mps/MPSStream.mm
- aten/src/ATen/native/mps/operations/LossOps.mm
> Set the default optimization level.

- aten/src/ATen/mps/MPSAllocator.h
- aten/src/ATen/mps/MPSAllocator.mm
- aten/src/ATen/native/mps/operations/ReduceOps.mm
- For the allocation requests that are within the range of [kMinRoundUpSize=1024 b, kMaxRoundUpSize=128 MB], we round up the allocation sizes to the next power of 2. This helps with sequential allocations with odd sizes (e.g., 1.11 MB, then 1.12 MB, ...) that would prevent older buffers in the pool to be reused due to their slightly smaller sizes compared to the new allocation size requests.
- Decreased the low watermark threshold to start garbage collection earlier
> Round up certain allocations to the next power of 2

- aten/src/ATen/native/mps/operations/Convolution.mm
- aten/src/ATen/native/mps/operations/Normalization.mm
1. up casting to fp32 for conv backward, batch_norm
2. down casting back to fp16 after execution
Fixes #ISSUE_NUMBER
> Fix amp errors

- torch/csrc/distributed/c10d/Ops.cpp
- torch/csrc/distributed/c10d/ProcessGroupGloo.cpp
- torch/distributed/distributed_c10d.py
1. register mps for gloo backend
2. register allgather_mps_
3. implement AsyncAllgatherMPSWork by copying tensor to cpu, do all_gather and copy back
Fixes #ISSUE_NUMBER
> Adding gloo mps all gather fall back support:

- torch/csrc/jit/serialization/unpickler.cpp
Fixes https://github.com/pytorch/pytorch/issues/88820, https://github.com/pytorch/pytorch/issues/87504
> Allow saved models to be loaded directly to MPS through torch.jit.load

- aten/src/ATen/mps/MPSProfiler.h
- aten/src/ATen/mps/MPSProfiler.mm
- Log monolithic CPU time for op executions which includes Graph compilation times.
- Added option to track memory growth after op execution to debug high memory usage issues.
- e.g.: `aten::copy_cast_mps:b8[2]:i32[2] (id=G4, run=1, gpu=0.010 ms, cpu=2.769 ms, mem=1.01 MB)`
- Fixed a bug in` "log_stats" `for `torch.mps.profiler.start()` python API.
- Display `Mean/Total CPU` times in logged stats when process terminates.
> Log CPU times and Memory Growth in MPSProfiler

- aten/src/ATen/native/mps/operations/Copy.mm
Replace `cast->copy` path through graph with a direct kernel doing both cast and copy.
> Add copy cast kernel

- aten/src/ATen/native/mps/operations/TensorCompare.mm
> Fix the FP16 clamp issue.
