kulinseth/pytorch

aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/BinaryOps.mm

This fix should improve the performance in many benchmarks as well.

Fix the issue with the rapid growth in memory allocations in Binary Ops (#77753)

---

aten/src/ATen/mps/MPSAllocator.h

This should prevent the Metal backend from discarding or recycling our MPS heaps.

Fix the issue with Metal Heap's volatility (#77829)

---

aten/src/ATen/mps/MPSDevice.mm

Update the version check.

---

aten/src/ATen/mps/MPSAllocator.h
aten/src/ATen/mps/MPSAllocator.mm
aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/Copy.mm

Remove view from graph cache when underlying buffer is freed

---

aten/src/ATen/native/mps/operations/Copy.mm
test/test_mps.py

Fix chaining of view tensors having a different shape than the parent tensor. Add tests from `test_view_ops.py` to `test_mps.py`.
Fixes the following example where 4 narrow calls are involved:
```
def test_constant_pad(self):
m = torch.nn.ConstantPad2d((-2, -2, -2, -2), 3.5)
input_cpu = torch.randn(1, 16, 16, 16)
input_mps = input_cpu.detach().clone().to("mps")
r_cpu = m(input_cpu)
r_mps = m(input_mps)
self.assertEqual(r_cpu, r_mps.to("cpu"))
```

Fix chaining of view tensors with a shape different to the parent tensor

---

aten/src/ATen/native/mps/operations/Copy.mm

Do a lookup for the parent tensor only if there's no graph already created.
Thanks @razarmehr for the suggestion.

Fix lookup of the parent tensor in as_strided

---

aten/src/ATen/native/mps/operations/LossOps.mm
test/test_mps.py

Fixes https://github.com/pytorch/pytorch/issues/79527
Added more tests for BCE (which all pass)
DCGAN still works with this change

Add fix for squeezed input axes handling

---

aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/ReduceOps.mm
aten/src/ATen/native/native_functions.yaml
test/test_mps.py

Backward now works, because of fixed casting in binary ops

Add amax and amin with tests

---

aten/src/ATen/mps/MPSAllocator.h
aten/src/ATen/mps/MPSAllocator.mm
aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/BinaryOps.mm
aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/View.mm
test/test_mps.py

- This patch should improve performance of view ops by creating much fewer mps graphs.
- Moved all code related to View ops into new file View.mm
- Fixed non-contiguous output of BinaryOps and added its test case in test_as_strided()
- Track the base shape of views in MPSAllocator's BufferBlock
- Some cleanup and refactoring

Replace constant scalars with placeholders in View Ops

---

aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/View.mm
test/test_mps.py

Performance improvement for copy_kernel_mps .
If dst is contiguous and there is no byte offset, we can save directly the result of gather into dst. This reduces the overhead of doing an additional blit for most cases.

Perf. improvement - save the gather result into dst directly if dst is contiguous (copy_kernel_mps)

---

aten/src/ATen/native/mps/operations/LossOps.mm
test/test_mps.py

Issue observed in TestConsistency

Handle 1D inputs

---

aten/src/ATen/mps/MPSStream.h
aten/src/ATen/mps/MPSStream.mm
aten/src/ATen/native/mps/operations/Copy.mm

Commit and continue

---

aten/src/ATen/native/mps/operations/Shape.mm
test/test_mps.py

Fixes https://github.com/pytorch/pytorch/issues/80850

Stack with bool input

---

aten/src/ATen/mps/MPSDevice.mm
aten/src/ATen/native/mps/operations/Indexing.mm

Build the indexing library with the correct Metal version
Default version is 1.2 if not specified on x86

Build the indexing library with the correct Metal version

---

aten/src/ATen/native/mps/operations/Copy.mm
test/test_mps.py

Fixes https://github.com/pytorch/pytorch/issues/80844, https://github.com/pytorch/pytorch/issues/81567

Get the correct size of the view tensor when copying from cpu to mps

---

torch/testing/_internal/common_device_type.py
torch/testing/_internal/common_utils.py

Add back support for `PYTORCH_TEST_WITH_MPS`

Enable mps unit testing

---

aten/src/ATen/native/mps/operations/PointwiseOps.mm

Also remove the unnecessary resize (structured op)

Return input in addcmul/div if value is zero

---

aten/src/ATen/native/mps/operations/Convolution.mm
test/test_mps.py

Fixes https://github.com/pytorch/pytorch/issues/83180, https://github.com/pytorch/pytorch/issues/82921, https://github.com/pytorch/pytorch/issues/82711, https://github.com/pytorch/pytorch/issues/82563
According to the pytorch [doc](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html), if a tuple of ints is passed, the first one is the height dimension, and the second one is the width dimension:
```
The parameters kernel_size, stride, padding, dilation can either be:
- a single int – in which case the same value is used for the height and width dimension
- a tuple of two ints – in which case, the first int is used for the height dimension, and the second int for the width dimension
```

Fix conv1D and conv2D with non-matching strides/paddings

---

aten/src/ATen/native/mps/OperationUtils.mm
test/test_mps.py

Fixes https://github.com/pytorch/pytorch/issues/82543
The current Placeholder code relies to find a gather graph in order to make the data `contiguous`, otherwise we'll try calling into `tensor.contiguous()` directly, which for slice elements, won't do anything.
E.g  consider the following basic case where we index a 2 element tensor:
```
tensor_list = torch.tensor([1.2, 1.0], device="mps")
for scalar in tensor_list:
r_mps = torch.ceil(scalar)
r_cpu = torch.ceil(scalar.to("cpu"))
self.assertEqual(r_mps.cpu(), r_cpu)
```
The second element `1.0` is a contiguous view tensor (similar to slicing), but it has no gather graph created behind. In the placeholder, we won't be able to find the graph, thus relying on the fallback case where we call `_tensor = src.contiguous();`. For an already …

Fix placeholder case for missing gather graph

---

aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/Normalization.mm
test/test_mps.py

Fixes: 
- https://github.com/pytorch/pytorch/issues/82566
- https://github.com/pytorch/pytorch/issues/80800
- mps->cpu casts from a smaller dtype to a bigger dtype
- mps->mps cast from smaller/bigger dtype to another dtype in case of scatter 
For `mps->cpu` copies where we don't have a source/destination offset, we can save the cast result directly in the destTensor,  so we can skip the additional overhead of the blit. In case we can return the data without doing the blit,  we need to check if it's blocking call, case in which we'd need a `synchronize(SyncType::COMMIT_AND_WAIT);` call (previously this was done by the blit).

Fix mps to cpu casting from a smaller dtype to a bigger dtype

---

aten/src/ATen/native/mps/operations/AdaptivePooling.mm
test/test_mps.py

Fixes #80732
However, the case where output width is smaller than input width, and output height is larger than input height (and vice versa), is not supported.

Enable adaptive avg pool 2d with larger output size than input size

---

test/test_mps.py

Exclude split float32 from test consistency

---

aten/src/ATen/native/mps/operations/ReduceOps.mm
test/test_mps.py

Also fix handling of negative reduction dims

Fix memory error in var

---

aten/src/ATen/native/mps/operations/Convolution.mm
test/test_mps.py

Fixes https://github.com/pytorch/pytorch/issues/84511
- Use the same logic as in the forward pass for the backward pass (in case of channels last, manually set the shape to `NHWC`)

Fix conv1d backwards crash for channels last case

---

aten/src/ATen/native/mps/operations/LossOps.mm
aten/src/ATen/native/mps/operations/RnnOps.mm

- This fixes leaks for MPSGraphTensorData which wrap the allocator buffers and would cause their retainCount to not reach 1.

Fix memory leaks that cause the buffers not to be released and cause OOM

---

aten/src/ATen/mps/MPSAllocator.h
aten/src/ATen/mps/MPSAllocator.mm
aten/src/ATen/mps/MPSStream.h
aten/src/ATen/mps/MPSStream.mm
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/View.mm

- Enable low watermark limit to detect memory pressure.
- Enable garbage collection and adaptive commit strategies when under memory pressure.
- More efficient resource management by splitting large heaps (instead of reusing oversized buffers for smaller allocation requests)
- Introduce Extra Large heaps to improve performance by avoiding numerous costly allocation of smaller heaps
- Fix purgeability when releasing the Metal heaps
Fixes Issue #79283

Improve memory usage and performance utilizing garbage collector and adaptive commit

---

aten/src/ATen/native/mps/operations/BinaryOps.mm
test/test_mps.py

Output of input shape [0,1,2] should be [0,1,2], not [0] i.e. delay returning from empty input condition to resize/reshape the output accordingly

Handle output shape for empty input in binary ops

---

aten/src/ATen/native/mps/operations/View.mm

Replace gather side of as_strided mps implementation when possible with MPSGraph shape APIs gives notable perf gain over existing path, roughly equal to the perf gain from using a custom metal kernel. 
Correctness checked by running test_mps.py

Implement as_strided using existing MPSGraph Shape APIs

---

aten/src/ATen/mps/MPSFallback.mm
aten/src/ATen/native/mps/operations/Indexing.mm
aten/src/ATen/native/native_functions.yaml
test/test_mps.py

Reuses the `index.Tensor_out` implementation since it's already expanding the bool/byte indices to long tensors.

Add support for aten::masked_select on mps

---

test/test_mps.py

I had forgotten to rename the new test, and it had an issue with the helper function, it now works as intended

Fix scatter scalar test

---

aten/src/ATen/native/mps/operations/View.mm
test/test_mps.py

Fixes https://github.com/pytorch/pytorch/issues/84364, https://github.com/pytorch/pytorch/issues/85592
Fixes bug for view ops where the base shape would be incorectly determined.
E.g for the following tensor `torch.tensor([0.5, 0.5], device="mps")[1][None]`, we could consider the base shape of the parent tensor as 1, while the actual base shape is 2.

Fix base shape size for view ops in case of multiple slices

---

aten/src/ATen/native/mps/operations/TensorCompare.mm
test/test_mps.py

Inputs with different number of dimensions but compatible shapes were being rejected
e.g. x.shape = [10,1,10]
y.shape = [10,10]
cond.shape = [10,10,1]

Handle compatible inputs to where

---

aten/src/ATen/Context.h
aten/src/ATen/detail/MPSHooksInterface.cpp
aten/src/ATen/detail/MPSHooksInterface.h
aten/src/ATen/mps/MPSGeneratorImpl.h
aten/src/ATen/mps/MPSGeneratorImpl.mm
aten/src/ATen/mps/MPSHooks.cpp
aten/src/ATen/mps/MPSHooks.h
aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/Distributions.mm
test/test_mps.py
torch/csrc/Generator.cpp

This patch will add support for creating torch.Generator for MPS device, and enables its functions such as manual_seed, get_state, and set_state.
Fixes #84288, #84516

Add MPSGenerator to enable custom random number generators on MPS backend

---

aten/src/ATen/native/mps/operations/BitwiseOps.mm

Fixes bitwise_not crash on AMD for empty dispatches:
```
test_output_match_bitwise_not_cpu_int16 (__main__.TestConsistencyCPU) ... zsh: floating point exception  python3 test_mps.py --verbose -k test_output_match_bitwise_not_cpu_int16
```

Fix empty dispatch for bitwise_not

---

aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/View.mm

- Fix the type mismatch bug if returning early from copy_kernel_mps when copy_cast is needed
- Create the view graph in gatherViewTensor instead of as_strided
- Fix the crash in asStridedLayer_reshapePattern() caused by negative srcDim

Fix the base shape of view tensor in as_strided_mps

---

aten/src/ATen/native/mps/operations/ReduceOps.mm
test/test_mps.py

Reduction ops don't support long dtypes. This PR takes care to assert when int64 is used for min / max reductions ops.
All other integer dtypes are casted to int32.

Exclude long dtype from reduction ops (min/max)

---

aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/View.mm

Fixes copies into slices where the input data type is different than the output dtype.
This change removes the cast done before scatter, so we don't have to allocate additional memory to perform the casting. Scatter handles the casting directly now.
```
device = "mps"
shape = (4, 4)
tensor = torch.randint(10, shape, device=device)
tensor_before = tensor.clone()
res = torch.empty(shape[0], shape[1] * 2, device=device)[:, ::2].copy_(tensor)
torch.testing.assert_close(tensor, tensor_before)
```

Add suport for casting updatesTensor to match outputTensor dtype directly in scatter

---

aten/src/ATen/native/mps/operations/Distributions.mm

Fixes multinomial crash happening on AMD:
```
test_multinomial (__main__.TestNLLLoss) ... 2022-10-21 10:55:57.184 python3[96212:646664] Error getting visible function:
(null) error: invalid qualified function name 'bandPartOp_0_m-2147483648__f'
/AppleInternal/Library/BuildRoots/4883e71d-37bd-11ed-b0ef-b25c5e9b9057/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Utility/MPSKernelDAG.mm:785: failed assertion `Error getting visible function:
(null) error: invalid qualified function name 'bandPartOp_0_m-2147483648__f'
```

Fix multinomial crash for negative values in bandOP

---

aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/View.mm
test/test_mps.py

Fixes https://github.com/pytorch/pytorch/issues/86975
If the destination is a strided MPS tensor and the source is a CPU tensor, we cannot perform a blit directly to copy the memory from the CPU tensor into the MPS tensor. We need to scatter the data into the right indices.
```
a1 = torch.Tensor([[1,2],[3,4], [5,6]]).to(torch.device("mps"))
b1 = torch.Tensor([-1, -1])
a1[1:,1] = b1  # strided MPS destination / contiguous CPU source
```

Add support for copying cpu tensors into strided mps tensors

---

aten/src/ATen/mps/MPSFallback.mm
aten/src/ATen/native/mps/operations/Indexing.mm
aten/src/ATen/native/native_functions.yaml
test/test_mps.py

Adds nonzero support for mps:
```
// Pseudocode:
//
// inputTensor   = [1,  0,  0,  3]
// inputNonZero  = [1,  0,  0,  1] (input != 0)
// scan          = [1,  1,  1,  2] (prefix sum)
// maskedIndices = [0, -1, -1,  1] (select)
// coordinates   = [0,  1,  2,  3] (coordinateAlongAxis)
// scatterResult = [0,  3]         (scatter)
```

Add nonzero support for mps

---

aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/UnaryOps.mm
test/test_mps.py

Skip gather/blit calls in case of strided output - this prevents:
- allocating additional memory for the output
- additional transpose for both the input and output
Fixes:
```
x = torch.rand((256,10), device='mps')
x = x.permute(1,0)
x.exp()
```

Skip gather/blit calls in case of strided output

---

aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/View.mm

Fixes https://github.com/pytorch/pytorch/issues/85297, https://github.com/pytorch/pytorch/issues/86048
Below are the results from the script provided by @Birch-san in https://github.com/pytorch/pytorch/issues/85297#issuecomment-1279625643:
**RC5**:
```
for reference: our sync operation -- on a tensor of our target size -- is responsible for only 0.1339 seconds of overhead
einsum 0 iteration 0 took 0.1471 seconds
einsum 0 iteration 1 took 0.0172 seconds
einsum 0 iteration 2 took 0.0155 seconds
einsum 0 iteration 3 took 0.0153 seconds
einsum 0 iteration 4 took 0.0157 seconds
einsum 0 iteration 5 took 0.0159 seconds
einsum 0 iteration 6 took 0.0158 seconds
einsum 0 iteration 7 took 0.0159 seconds
einsum 0 iteration 8 took 0.0159 seconds
einsum 0 iteration 9 took 0.0159 seconds
10 iterations …
```

Solve contiguos view tensors using arrayViews instead of blits

---

aten/src/ATen/native/mps/operations/Unique.mm
aten/src/ATen/native/native_functions.yaml
test/test_mps.py

Adds MPSGraph implementation for unique and unique_consecutive. Currently not possible to support unique with dim argument, as these requires sorting with tensor keys, rather than scalar keys.

Add mps implementation for unique(no dim support) and unique_consecutive

---

aten/src/ATen/native/mps/operations/Pad.mm
test/test_mps.py

- Put constant value in the key
- Fix crash when grad_output.numel() is 0
- Fill output tensor when input.numel() is 0
- Move constant_pad_nd's from block list to allow list in TestConsistency

Fix padding dimension issues with constant_pad_nd

---

aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/operations/ReduceOps.mm
aten/src/ATen/native/native_functions.yaml
test/test_mps.py

Add support for cdist on mps

---

aten/src/ATen/mps/MPSDevice.h
aten/src/ATen/mps/MPSDevice.mm
aten/src/ATen/native/mps/operations/Distributions.mm
aten/src/ATen/native/mps/operations/Indexing.mm
aten/src/ATen/native/mps/operations/Unique.mm
test/test_mps.py

Fixes TestConsistency masked_fill for bool data type.
Casting a tensor > 1 to `MPSDataTypeBool` will result in 0 instead of 1. This change manually casts the scalar to a value of 0 or 1 when casting a non-boolean tensor to a boolean tensor:
```
(inputDataType == MPSDataTypeBool) ? !!value.to<double>() : value.to<double>()
```

Fix MPSGraph casting issue to MPSDataTypeBool in masked_fill op

---

aten/src/ATen/native/mps/operations/BinaryOps.mm
test/test_mps.py

Also remove the double cast to boolean in comparison ops

Cast to unsigned type when comparing signed vs. unsigned integers in BinaryOps

---

aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/View.mm
test/test_mps.py

There are cases when the arrayViewTensor API cannot be used to solve the view operations, such as when a view dimension is bigger than the base dimension of the tensor, e.g:
```
base shape: [1, 768, 512, 2] // we cannot slice the base shape in any way to result in first dimension `2`
view shape: [2, 384, 512, 1] 
```
On such cases, we need to fallback on the gather code (that detects this is a slice followed by a reshape) to solve this issue.

Fallback on gather code to solve view tensors when a slice is followed by a reshape

---

aten/src/ATen/native/mps/operations/ReduceOps.mm
test/test_mps.py

- fix type mismatch
- add correction parameter to bessel correction calculation
- use unbiased (correction=1) std / var by default

Fix std and var for float16 and float32

---

aten/src/ATen/native/mps/operations/ReduceOps.mm
test/test_mps.py

Fixes `masked.argmax / masked.argmin`
In case of passing `inf` to argmax / argmin, MPS will return nan as index for these numbers. Casting this `nan` to Long will make it `-1`. This change avoids negative values by clamping them to 0 (matching CPU results).

Clamp argmin / argmax min indicies values to 0

---

test/test_mps.py

Issues with masked_var & masked_std resolved by changes made in https://github.com/kulinseth/pytorch/pull/188. Moving tests to allowlist

Removed masked_var & masked_std from blocklist

---

aten/src/ATen/native/mps/operations/Indexing.mm
aten/src/ATen/native/mps/operations/TensorCompare.mm
test/test_mps.py

Fix `masked_fill` and `masked_mean` hang for bool data type on macOS Monterey.
`selectWithPredicateTensor` hangs the machine when using bool data type on macOS Monterey (this is fixed in Ventura). Instead of using bool, this PR changes the input data type to int8.

Fix masked_fill and masked_mean hangs on macOS Monterey

---

aten/src/ATen/native/mps/operations/View.mm

Fixes correctness issue in `test_output_match_einsum_cpu_float32`. 
Summary:
Currently, the following view operation will go through the optimized view path, creating the following graph:
```
bmm_out_mps_impl:Float32[1,3,4]:Float32[1,4,4]
gather:Float32[4,4,]:[1,4,4,]:[16,1,4,]:[0]
func @main() {
%0 = "mps.placeholder"() : () -> tensor<4x4xf32>
%1 = "mps.placeholder"() : () -> tensor<1xi32>
%2 = "mps.placeholder"() : () -> tensor<1xi32>
%3 = "mps.placeholder"() : () -> tensor<1xi32>
%4 = "mps.placeholder"() : () -> tensor<1xi32>
%5 = "mps.constant"() {value = dense<[1, 4, 4]> : tensor<3xi32>} : () -> tensor<3xi32>
%6 = "mps.constant"() {value = dense<-1> : tensor<i32>} : () -> tensor<i32>
%7 = "mps.get_coordinates"(%5, %6) : (tensor<3xi32>, tensor<i32>) -> tensor<1x4x4xi32>
%8 = …
```

Fix expand pattern when strides of src/dst are not matching

---

aten/src/ATen/mps/MPSAllocator.h

Also decreased low watermark ratio to start garbage collection and adaptive commit earlier

Enable high watermark ratio to limit the memory allocations

---

test/test_mps.py

Move as_strided_scatter to random output blocklist, dup update indices may result in non-deterministic result.

Move as_strided_scatter to random output blocklist

---

aten/src/ATen/native/mps/operations/UnaryOps.mm

This should fix the crash with `TestConsistencyCPU.test_output_match_nn_functional_softsign_cpu`

Fix the crash in sgn_out_mps()

---

aten/src/ATen/native/mps/operations/ReduceOps.mm

- The shape of input and indices tensors were missing in the cached key
- Use the following to repro the crash:
`python test/test_mps.py -v TestConsistencyCPU.test_output_match_max_reduction_with_dim_cpu_float32 TestNLLLoss.test_max_el`

Fix the crash in max_out_mps() caused by cached key conflict

---

aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/BinaryOps.mm
aten/src/ATen/native/mps/operations/Indexing.mm
aten/src/ATen/native/mps/operations/Repeat.mm
aten/src/ATen/native/mps/operations/ScatterGather.mm
aten/src/ATen/native/mps/operations/Shape.mm
aten/src/ATen/native/mps/operations/UnaryOps.mm
aten/src/ATen/native/mps/operations/View.mm

Summary:
- Remove redundant bool casts from scatter/gather
- Make the workarounds for scatter/gather (for bool/uint8 data types) OS specific - use them only in macOS Monterey, ignore them starting with macOS Ventura 
- Make all tensors ranked in scatter
Fixes following tests: 
```
test_output_match_slice_scatter_cpu_bool
test_output_match_select_scatter_cpu_bool
test_output_match_diagonal_scatter_cpu_bool
test_output_match_repeat_cpu_bool
test_output_match_rot90_cpu_bool
etc..
```
Still failing on macOS Monterey (needs additional investigation):
```
test_output_match_scatter_cpu_bool
```

Fix ops with bool issues in macOS Monterey

---

aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/BinaryOps.mm
aten/src/ATen/native/mps/operations/PointwiseOps.mm
aten/src/ATen/native/mps/operations/Shape.mm
aten/src/ATen/native/mps/operations/UnaryOps.mm
test/test_mps.py

- Shortened the cached graph string key for `cat_out_mps()`
- Removed the unused `use_scalar_value` from `getTensorsStringKey()`
- Clean up and refactoring

Fix the ChannelsLast memory format in cat_out_mps()

---

test/test_mps.py

Also create a list of ops that would be allowed to differ up to values defined by rtol/atol with FP16

Add rtol/atol to the assertEqual() in gradient results check

---

aten/src/ATen/native/mps/MPSGraphVenturaOps.h
aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/operations/Distributions.mm
aten/src/ATen/native/mps/operations/Inverse.mm

Fix build errors (`WERROR=`1) caused by unrecognized macOS Ventura selectors.

Fix unrecognized selector build warnings in macOS Monterey

---

aten/src/ATen/native/mps/operations/Distributions.mm

Fixes `test_randperm` on macOS Moneterey

Fix randperm CPU fallback for macOS Monterey

---

aten/src/ATen/native/mps/operations/Indexing.mm

Remove unused pragma - the missing selector is already handled by `MPSGraphVenturaOps.h`

Remove unused pragma

---

aten/src/ATen/native/mps/operations/ReduceOps.mm
test/test_mps.py

Only FP16, FP32 and I32 are working fine with reductions ops - every other integer data type should be casted to I32.

Fix min/max_reduction_with_dim ops

---

aten/src/ATen/native/mps/operations/LossOps.mm
test/test_mps.py

Fixes test regressions seen in test_nll_loss_empty_tensor_reduction_none, test_nll_loss_empty_tensor_reduction_mean, test_nll_loss_empty_tensor_reduction_sum. Sets target_axis to 1, but avoids backwards_pass crash by properly multiplying input channels by corresponding weights

Correctly apply weights to oneHotTensor in NLLLoss

---

aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/LinearAlgebra.mm
aten/src/ATen/native/native_functions.yaml

Add triangular solve op support through MPS `MPSMatrixSolveTriangular` kernel

Add triangular solve op through MPSMatrixSolveTriangular

---

aten/src/ATen/native/mps/operations/Normalization.mm
test/test_mps.py

- fix batch_norm_mps_out key
- return 1/sqrt(var+epsilon) instead of var
- return empty tensor for mean and var if train is not enabled
- remove native_batch_norm from block list

Fix batch_norm_mps

---

test/test_mps.py

- unlock _native_batch_norm_legit after resolving native_batch_norm

Remove _native_batch_norm_legit from blocklist

---

aten/src/ATen/native/mps/operations/GridSampler.mm

Fixes crashes on Ventura happening with SDK older than 13.1

Skip compilation of mps grid sampler for macos older than 13.1

---

test/test_mps.py

Use os module to get absolute path to cuda_results.yaml file

Fix relative paths in test_mps

---

aten/src/ATen/native/mps/operations/Activation.mm
test/test_mps.py

- fix gelu_out_mps key
- add calculation for gelu with tanh
- remove gelu from blocklist

Fix nn.functional.gelu

---

aten/src/ATen/native/mps/operations/View.mm
test/test_mps.py

Add more patterns to check if a tensor is reshaped so it prevents going through the arrayViewSlice code:
e.g this can be solved through arrayViews:
```
x = torch.randn([1, 4096, 2], device="mps")
y = x[1, :2048]
```
but this doesn't:
```
x = torch.randn([1, 4096, 2], device="mps")
y = x[1, :2048].reshape([1, 4096]) 
```

Add additional checks for reshaped views

---

test/test_mps.py

Fixes dictionary searches in case of multiple keys are present in different dicts (e.g pow in FAST MATH dict and in  EXPECTED_FAILURES)

Fix blocklist dict search

---

aten/src/ATen/native/mps/operations/Activation.mm

- Also fix indentation and formatting

Fix the crash with hardswish_backward

---

aten/src/ATen/native/mps/operations/Normalization.mm
test/test_mps.py

- add revert caculation for save_var used in backward path
- add backward test for native_batch_norm and _native_batch_norm_legit

Fix batch_norm_backward_mps

---

test/test_mps.py

- remove interpolate from blocklist since it works
- move interpolate_area to unimplemented list

Use low precision for FP16 for divtrunc_rounding

---

aten/src/ATen/native/mps/operations/BinaryOps.mm
test/test_mps.py

- report error for int64
- for int16,int32 cast tensor to float, divide than floor
- unblock floor_divide and divfloor_rounding from testing

Fix floor_divide

---

aten/src/ATen/native/mps/operations/ReduceOps.mm
aten/src/ATen/native/mps/operations/Unique.mm
test/test_mps.py

- fix num_output_dims calculation
- fix median_out_mps key
- cast tensor sent to sortWithTensor and argSortWithTensor, and cast back for output
- note down same issue for unique
- unblock median from blocklist

Fix and unblock TestConsistency for median

---

test/test_mps.py

- unblock nn.functional.softplus test
- unblock test_softplus test

Remove softplus from blocklist

---

aten/src/ATen/native/mps/operations/UnaryOps.mm
test/test_mps.py

Add support for negative dimensions in cumsum

---

aten/src/ATen/native/mps/operations/Normalization.mm
test/test_mps.py

- remove the duplicate calculation from layer_norm_mps
- enable native_layer_norm backward test
- raise atol rtol for native_layer_norm

Fix layer norm

---

aten/src/ATen/native/mps/operations/View.mm

- When we do slicing in `asStridedLayer_genericPattern()`, the destination's offset + length could be larger than sources length, causing the following crash on Monterey:
`MPSNDArrayDescriptor sliceDimension:withSubrange:] error: the range subRange.start + subRange.length does not fit in dimension[0] (3)`
- Here's a test case to reproduce this crash on Monterey:
```
def test_stack_tuple(self):
values = [[[0, 0], [0, 0]],
[[0, 0], [0, 0]],
[[1, 1], [0, 0]]]
mps_x = torch.tensor(values, device='mps', dtype=torch.int32)
tup1 = torch.nonzero(mps_x, as_tuple=True)
tup2 = torch.stack(tup1) # <---------------------- crashes here
print(tup2)
```

Fix the crash in View ops when slicing wrong length

---

test/test_mps.py

- add blocklist for macOS 12
- move nn.functional.conv_transpose2d to the macOS 12 blocklist
- add allowlist for macOS 13.3
- move nn.functional.conv_transpose2d, pow, __rpow to the macOS 13.3 allowlist

Adding blocklist for macOS 12

---

torch/backends/mps/__init__.py
torch/csrc/mps/Module.cpp
torch/mps/__init__.py

- This patch fixes a regression caused by recent MPS module interface. Since we now compile `torch._C._is_mps_available()` only if `USE_MPS` is defined, then it may cause failures on CUDA (and other devices where `USE_MPS` is not defined), if we upstream. So, this patch checks if `is_mps_available` is implemented first and then calls it.
- Also use the unique name `default_mps_generator` to avoid conflicts with CPU default generator

Fix is_mps_available() regression on non-MPS devices

---

aten/src/ATen/native/mps/operations/LinearAlgebra.mm

- ignore input when beta is 0, so that nan and inf will not be propagated.

Fix addmm calculation:

---

aten/src/ATen/native/mps/operations/Activation.mm
aten/src/ATen/native/mps/operations/Indexing.mm
aten/src/ATen/native/mps/operations/Linear.mm
test/test_mps.py

- This should fix the hard crashes reported in BLOCKLIST_OP_GRAD such as sigmoid, tanh, masked_fill, linear, prelu, etc.
- The prelu now fails with correctness issues so I kept it in the blocklist

Fix crashes in several backward ops

---

aten/src/ATen/native/mps/operations/LossOps.mm
test/test_mps.py

- Take grad_output into account when computing smooth_l1_loss_backward()
- Add numel()==0 check to prevent crashes
- Clean up and formatting

Fix correctness issues with smooth_l1_loss_backward()

---

test/test_mps.py

- This patch moves several Grad tests related to FP16 precision from block list to FP16_LOW_PRECISION_LIST which should produce correct output.

Fix FP16 precision issues for Grad tests

---

aten/src/ATen/native/mps/operations/Pooling.mm
test/test_mps.py

- Add divisor to cached string key to avoid conflicts
- Fallback to CPU when divisor is passed for int64 input types
- Remove MaxPool2D from UNIMPLEMENTED_OP list (was put there by mistake)
- Add test case when both ceil_mode and count_include_pad are True (previously failed).

Fix wrong results in AvgPool2D when count_include_pad=True

---

test/test_mps.py

The test shows to('mps') op fails in the case, which requires a fix.

Add a unit test for to op 

---

aten/src/ATen/native/mps/operations/AdaptivePooling.mm
test/test_mps.py

- Warn and fallback to CPU for AdaptiveAvgPool2d if input/output sizes are not divisible
- Remove the redundant blocking copies from AdaptiveMaxPool2d
- Clean up redundant code and headers

Fix issues with adaptive average and max pool2d

---

aten/src/ATen/native/mps/operations/LinearAlgebra.mm
aten/src/ATen/native/mps/operations/TriangularOps.mm
test/test_mps.py

- make input tensors contiguous before computing solve_triangular()
- fix the crashes in triu and tril ops due to missing numel()==0 checks
- zero out result of bmm() when numel()==0 check is true (otherwise fails solve_triangular_backward tests)

Fix correctness issues in solve_triangular()

---

test/test_mps.py

- block tests that are failing on git runner for macOS 12

Fix macOS 12 blocklist:

---

aten/src/ATen/native/mps/operations/LinearAlgebra.mm

Disable CPU fallback for triangular solve since MPS already supports the API in Monterey

Disable CPU fallback for triangular solve on Monterey and use MPS instead

---

test/test_nn.py
test/test_ops.py

Enable test_nn and test_ops to run on mps without segfaulting
Important failures listed below (big difference in atol and rtol diff).
- **test_nn.py** failures:
```
test_rnn_retain_variables_mps_float32
test_nonlinearity_propagate_nan_mps
test_nll_loss_total_weight_is_zero_mps
test_nll_loss_all_ignored_mps
test_cross_entropy_label_smoothing_weight_ignore_indices_mps
test_cross_entropy_label_smoothing_consistent_index_target_and_probs_mps
```
- **test_ops.py** failures:
```
test_backward_repeat_interleave_mps_float32
test_backward_nn_functional_upsample_nearest_mps_float32
test_backward_nn_functional_bilinear_mps_float32
test_backward_gradient_mps_float32
test_backward_gather_mps_float32
test_operator_trapezoid_mps_float32
test_operator_nn_functional_avg_pool2d_mps_float32 …
```

Enable test_nn and test_ops to run on mps

---

aten/src/ATen/native/mps/operations/ScatterGather.mm
test/test_mps.py

Fixes TestConsistency.scatter on macOS 12

Downstream scatter fix for bool from upstream

---

.github/workflows/_mac-test-mps.yml
.github/workflows/lint.yml
test/test_modules.py

Enable `test_modules.py` to run on MPS and CI runners. 
During bringup, The CI runners will just run this file but it won't treat it as an error.

Enable test modules on MPS and CI runners

---

aten/src/ATen/native/mps/operations/Convolution.mm
test/test_mps.py

- add _mps_convolution_impl that takes optional shape
- for conv_tranpose2d grad, use the shape from forward pass directly
- for conv, calculate the shape from input
- remove nn.functional.conv_transpose2d grad from blocklist

Fix nn.functional.conv_transpose2d grad

---

aten/src/ATen/native/mps/operations/Normalization.mm

Fixes `test_modules.py` batch norm NHWC testcases:
- `test_memory_format_nn_BatchNorm2d_eval_mode_mps_float32` 
- `test_memory_format_nn_BatchNorm2d_eval_mode_mps_float32`

Fix batch norm for NHWC

---

aten/src/ATen/native/mps/operations/BinaryOps.mm
aten/src/ATen/native/native_functions.yaml
test/test_mps.py

Map remainder op to the same template as div

Fix remainder op for integral dtypes

---

test/test_mps.py

Unique was listed as having a correctness failure, but this was only because it always sorts the output and CPU does not. Moving to expected failures, as MPSGraph does not support dim argument

Moved unique to expected failures due to dim argument not supported

---

test/test_mps.py

- move masked.normalize, masked.sum, outer, sum_to_size float16 to low precision list
- unblock bool, transpose
- mark interpolatenearest, upsample_nearest, conv_transpose2d as expected

Update macOS 12 blocklist

---

aten/src/ATen/native/mps/operations/BinaryOps.mm
aten/src/ATen/native/mps/operations/UnaryOps.mm
test/test_mps.py

[CHERRY-PICK] Block uint8 data type for unary and binary ops on macOS 12. (#313)

---

aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/ReduceOps.mm
test/test_mps.py

Fixes backward pass for bilinear.
Summary of changes:
- bilinear op is able to produce **contiguous, non-view** tensors with a storage offset, such as: shape=`[1, 1, 1, 1]`, `storage_offset=12`. This seems a weird case, but it is valid, and for these type of tensors we wouldn't be able to gather/scatter since we look at the view flag (which is not here). This change looks into storage_offset only rather than the is_view flag which is not being set
- **reduction sum** must return a zeroed out output if passing an input with 0 elements (e.g a shape of (0, 5)).

Fix bilinear backward pass

---

aten/src/ATen/native/mps/operations/Convolution.mm

- add _mps_convolution_impl that takes optional shape
- for conv_tranpose2d grad, use the shape from input directly
- remove nn.functional.conv_transpose2d grad from blocklist

[CHERRY-PICK] Fix nn.functional.conv_transpose2d grad (#312)

---

aten/src/ATen/native/mps/operations/ReduceOps.mm
test/test_mps.py

Reduction cast f16 to f32 only on macOS 12

---

aten/src/ATen/native/mps/operations/Copy.mm
test/test_mps.py

- The copy_cast path requires storage_offset to be applied before casting
- This should fix the failure with GPT2 when use_cache=True

Fix copy_cast_mps() on tensors with storage offset

---

aten/src/ATen/native/mps/operations/View.mm

This should fix the problem in Resnet model with image artifacts due to saturation on int8 type and also the incorrect class recognition reported in #86954.

Fix the uint8 type issue with View ops kernels

---

aten/src/ATen/native/mps/operations/View.mm
test/test_modules.py
test/test_mps.py

Fixes slicing of view ops when both dimensions need to be sliced and the 2nd dimension to be sliced has an offset of 0.
e.g in case of base shape `[3, 4]` and view shape `[1, 2] storrage_offset=8`, both dimensions of the base shape would need to be sliced. The offset for the first element in the 2nd dimension is 0, which was causing the previous check ` if (nextSliceOffset)` to fail. This change fixes the condition so an offset of 0 won't be ignored.

Fix view op slicing for 2nd dim in case of 0 offset

---

aten/src/ATen/mps/MPSDevice.mm
aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/ReduceOps.mm
aten/src/ATen/native/mps/operations/Repeat.mm
aten/src/ATen/native/mps/operations/Sort.mm
aten/src/ATen/native/mps/operations/UnaryOps.mm
test/test_mps.py
test/test_mps_utils.py

MPS in macOS13.3 has added support for int64 in reduction ops / cumsum / sort / argsort. This change removes the hard-coded casts and error messages prior macOS 13.3, allowing the op to run natively with int64.

Remove casts from reduction/cumsum/sort ops starting with macOS 13.3

---

aten/src/ATen/native/mps/operations/View.mm
test/test_mps.py

Disallow reshapes for arrayViews.
Current code allows a base shape of `[2, 4, 256]` to be sliced into `[4, 1, 256]` (view's shape) - which is not possible. Slicing a smaller dimension into a bigger one will always error out.  
Fixes https://github.com/pytorch/pytorch/issues/95883

Disallow reshapes for arrayViews

---

aten/src/ATen/mps/MPSStream.h
aten/src/ATen/mps/MPSStream.mm
aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/BinaryOps.mm
aten/src/ATen/native/mps/operations/ReduceOps.mm
aten/src/ATen/native/mps/operations/UnaryOps.mm

Reduce the number of graph compilations for binary/unary/ops (helps with the cases when the shapes of the tensors keep changing very frequently)

Reduce numbers of graph compilations for unary/binary/reduction ops

---

aten/src/ATen/mps/IndexKernels.h
aten/src/ATen/mps/MPSDevice.h
aten/src/ATen/mps/MPSDevice.mm
aten/src/ATen/native/mps/operations/BinaryKernel.mm
aten/src/ATen/native/mps/operations/CrossKernel.mm
aten/src/ATen/native/mps/operations/Indexing.mm

Use bindless Argument Buffers / unbounded arrays from Metal 3 to write directly in the AB for advanced indexing kernels. This allows the PSO to be cached since we can fill directly the AB on the CPU.

Add PSO caching for advanced indexing kernels

---

aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/Indexing.mm
aten/src/ATen/native/mps/operations/Scalar.mm

Summary of changes:
- Calculate nonzero count first before running nonzero op
- allocate only 1 element when calling .item(), and blit only the size of destination
- Disable type inference for nonzero (output shape changes very frequently)

Calculate nonzero count first before running nonzero op

---

aten/src/ATen/mps/MPSFallback.mm
aten/src/ATen/mps/MPSProfiler.h
aten/src/ATen/mps/MPSProfiler.mm
aten/src/ATen/mps/MPSStream.mm
aten/src/ATen/native/mps/OperationUtils.mm

- This patch adds support for dumping info of the ops that fallback on CPU including CPU times and Copy Overhead (for copying input tensors to CPU and result back to MPS).
- Added signpost tracing for CPU fallbacks.
- Enabled capturing SIGINT to display profiling stats when process is terminated with CTRL+C.

Add CPU Fallback profiling, and capture SIGINT

---

aten/src/ATen/mps/MPSAllocator.h
aten/src/ATen/mps/MPSAllocator.mm
aten/src/ATen/mps/MPSAllocatorInterface.h
aten/src/ATen/mps/MPSStream.h
aten/src/ATen/mps/MPSStream.mm
aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/Scalar.mm

- This improves the copy performance and supports both H2D and D2H Scalar copies

Use memcpy() to copy scalar tensors on unified memory

---

aten/src/ATen/mps/MPSProfiler.h
aten/src/ATen/mps/MPSProfiler.mm
aten/src/ATen/native/mps/operations/Copy.mm

- This enables profiling copies that use memcpy on unified memory (i.e., try_copy_scalars_mps()) because they may sync with GPU and we need to trace them on Signposts.
- Added number of blocking and memcpy copies to copy stats.
- Refactoring and clean up

Support profiling for Scalar Copies

---

aten/src/ATen/mps/MPSStream.h
aten/src/ATen/mps/MPSStream.mm
aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/BinaryOps.mm
aten/src/ATen/native/mps/operations/ReduceOps.mm
aten/src/ATen/native/mps/operations/UnaryOps.mm
test/test_mps.py

Fixes perf regression in torchbench (Brings back changes from https://github.com/kulinseth/pytorch/pull/382)

Enable executable caching when type inference is disabled

---

aten/src/ATen/native/mps/operations/ReduceOps.mm
aten/src/ATen/native/mps/operations/UnaryOps.mm

Summary of changes:
- Reduction ops optimization - squeeze all dimensions after 4th dim if they are all 1
- Disable type inference only for 1D unary ops

Squeeze last dimensions if possible for 5D (or bigger) reductions

---

aten/src/ATen/mps/MPSAllocator.h
aten/src/ATen/mps/MPSAllocatorInterface.h
aten/src/ATen/mps/MPSStream.h
aten/src/ATen/mps/MPSStream.mm

- This should improve performance on some models that encode large resources onto command buffers, by committing adaptively based on the accumulated size of resources encoded.

Commit more frequently on command buffers with large resources

---

aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/Shape.mm

This should fix the recompilation issue with cat and its extremely long string keys

Make cat_out_mps() unranked

---

aten/src/ATen/mps/MPSStream.h
aten/src/ATen/mps/MPSStream.mm
aten/src/ATen/native/mps/operations/BinaryKernel.mm
aten/src/ATen/native/mps/operations/BitwiseOps.mm
aten/src/ATen/native/mps/operations/CrossKernel.mm
aten/src/ATen/native/mps/operations/Indexing.mm
aten/src/ATen/native/mps/operations/LinearAlgebra.mm
aten/src/ATen/native/mps/operations/View.mm

This will take into account the size of resources attached from native Kernel calls into the active command buffer, so we could commit adaptively if the accumulated sizes exceed the threshold.

Enable Adaptive Commit for kernel calls

---

aten/src/ATen/native/mps/operations/Copy.mm

This should fix this error from command buffers which is caused by the race condition from the synchronize() call from try_copy_scalars() and the encodeToCommandBuffer() call from executeMPSGraph():
`failed assertion `Completed handler provided after commit call'`

Fix the completedHandler error caused by race condition in try_copy_scalars()

---

aten/src/ATen/mps/MPSAllocator.h
aten/src/ATen/mps/MPSAllocator.mm
aten/src/ATen/mps/MPSAllocatorInterface.h
aten/src/ATen/mps/MPSProfiler.h
aten/src/ATen/mps/MPSProfiler.mm
aten/src/ATen/mps/MPSStream.h
aten/src/ATen/mps/MPSStream.mm
aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/BinaryOps.mm
aten/src/ATen/native/mps/operations/BitwiseOps.mm
aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/Scalar.h
aten/src/ATen/native/mps/operations/Scalar.mm
aten/src/ATen/native/mps/operations/View.mm

- Defer freeing buffers until completionHandler is called and their retainCount becomes <= 1.
- Introduce INCLUDE_BUFFER_ID option for MPSProfiler to assist debugging buffers that are involved with various ops.
- Refactor code for allocating MPSGraphTensorData to enable associating them with their underlying metal buffers
- Use lists for buffer pools to simplify iterating over the pools

Enable Scalar Binary/Bitwise ops for shared buffers

---

aten/src/ATen/mps/MPSAllocator.mm
aten/src/ATen/mps/MPSProfiler.h
aten/src/ATen/mps/MPSProfiler.mm
aten/src/ATen/mps/MPSStream.mm

- The growth was caused by a previous PR where we retained buffers longer than needed in the pending free state

Fix the memory growth caused by retaining inactive buffers

---

aten/src/ATen/test/mps_test_allocator.cpp
build_variables.bzl
caffe2/CMakeLists.txt
torch/csrc/api/include/torch/all.h
torch/csrc/api/include/torch/mps.h
torch/csrc/api/src/mps.cpp

This is a downstream of the already approved PR: #96668
- This enables the APIs `torch::mps::is_available()/synchronize()/manual_seed()` for use in PyTorch C++.
- Added test case for C++ APIs to `mps_test_allocator.cpp`

[Downstream] Add C++ API support for MPS backend (#96668)

---

aten/src/ATen/detail/MPSHooksInterface.h
aten/src/ATen/mps/MPSDevice.h
aten/src/ATen/mps/MPSDevice.mm
aten/src/ATen/mps/MPSHooks.h
aten/src/ATen/mps/MPSHooks.mm
torch/csrc/api/include/torch/mps.h
torch/csrc/api/src/mps.cpp
torch/csrc/mps/Module.cpp

This change adds the following C++ APIs for MPS backend: 
`torch::mps::get_command_buffer()`
`torch::mps::get_dispatch_queue()`
`torch::mps::commit()`

Add support for Custom Kernels

---

aten/src/ATen/mps/MPSStream.mm

- This change reverts a regression that was caused by a previous change to retain the command buffers after waitUntilCompleted call when commitAndContinue was enabled.
That regression caused the command buffers to retain references to the buffers and cause the memory to grow.

Fix memory growth regression caused by retaining command buffers

---

torch/mps/event.py

This should fix this error from the destructor of `torch.mps.Event` class:
`AttributeError: 'NoneType' object has no attribute '_mps_releaseEvent'`

Fix the Event's API releaseEvent error in destructor

---

aten/src/ATen/mps/MPSProfiler.h
aten/src/ATen/mps/MPSProfiler.mm
test/test_mps.py
torch/mps/profiler.py

This enables logging stats when the process terminates only for a specific scope of Python code

Add "log_stats" mode to torch.mps.profiler.start()

---

aten/src/ATen/native/mps/operations/BinaryKernel.mm
test/test_mps.py

Constant address space doesn't accept unaligned buffers, which will cause issues for view ops since these buffers can have any offset (e.g: 9, 15, 3).
This PR replaces `constant` address space with `const device`

Replace constant address space with const device

---

aten/src/ATen/native/mps/operations/Distributions.mm

These sanity checks would cause a costly gpu-cpu sync due to .item() calls. So we just check them in debug builds

Disable Multinomial sanity checks in Release builds

---

aten/src/ATen/native/mps/OperationUtils.h
aten/src/ATen/native/mps/OperationUtils.mm
aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/LinearAlgebra.mm
aten/src/ATen/native/mps/operations/Shape.mm
aten/src/ATen/native/mps/operations/SoftMax.mm

Also disable type inference for the unranked bmm, softmax, cat, and copy_cast ops

Fix a bug in disableTypeInference code

---

aten/src/ATen/native/mps/operations/Copy.mm
aten/src/ATen/native/mps/operations/LinearAlgebra.mm

Handle transposes in second batch of matrices in `bmm` op.
Improves `bmm` op perf if second matrix is transposed (row by row matrix multiplication is much faster compared to row by column since all memory is contiguous / no strided accesses are performed).

Handle transposes in second batch of matrices in bmm
